// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTpp_3o9BgW3xEKanxs2A2ZDX1bgkt8ic',
    appId: '1:323851825393:web:5f1d39babb34759ea53950',
    messagingSenderId: '323851825393',
    projectId: 'food-deliv-1',
    authDomain: 'food-deliv-1.firebaseapp.com',
    storageBucket: 'food-deliv-1.appspot.com',
    measurementId: 'G-250PNRN6LD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDunAtWRDS-WdWN3-eGpXf-z_2JSKgSRhQ',
    appId: '1:323851825393:android:bafcb6f69cc572dba53950',
    messagingSenderId: '323851825393',
    projectId: 'food-deliv-1',
    storageBucket: 'food-deliv-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWKjVuHJ8DVP0kxBZ_OvjNJ9gCaumIsSQ',
    appId: '1:323851825393:ios:2f06bf05ae7acfd5a53950',
    messagingSenderId: '323851825393',
    projectId: 'food-deliv-1',
    storageBucket: 'food-deliv-1.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWKjVuHJ8DVP0kxBZ_OvjNJ9gCaumIsSQ',
    appId: '1:323851825393:ios:2f06bf05ae7acfd5a53950',
    messagingSenderId: '323851825393',
    projectId: 'food-deliv-1',
    storageBucket: 'food-deliv-1.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTpp_3o9BgW3xEKanxs2A2ZDX1bgkt8ic',
    appId: '1:323851825393:web:47ce2cb4f80d9488a53950',
    messagingSenderId: '323851825393',
    projectId: 'food-deliv-1',
    authDomain: 'food-deliv-1.firebaseapp.com',
    storageBucket: 'food-deliv-1.appspot.com',
    measurementId: 'G-HBWXVXL88G',
  );
}
